[package]
name = "lucky-vicky-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
async-openai = "0.24.0"
dotenv = "0.15.0"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
