[package]
name = "lucky-vicky-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
kalosm = { git = "https://github.com/floneum/floneum", version = "0.3.2", features = ["language"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
